### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by Allam76** [cevou/openui5-webpack#1]
Hello. Thanks for a very interesting project.

Would it be possible to add an example or getting started?

**Comment by cevou** [comment]
You can find an example implementation here: https://github.com/cevou/openui5-sample-app/tree/webpack
Does this help or do you need additional information? What do you need to get started, so I can improve the README file?

**Comment by Allam76** [comment]
The example helps perfectly, thank you a ton! That is all I needed to get started.
