### ISSUE TITLE
Webpack 3 example?

### ISSUE THREAD

**Issue by areinmeyer** [cevou/openui5-webpack#6]
Hi!

I'm trying to setup a React/webpack/babel project we have to utilize some of the SAPUI5 code and came across this loader.  Unfortunately due to upstream issues we still have to use Webpack 3 for now.  Can you tell me at what version that webpack 3 was still supported?  And did that have any particular dependencies on the SAP/OpenUI5 version as well?

**Comment by cevou** [comment]
Hi Allan,

can you describe your plans a little bit more? Do you want to integrate SAPUI5 controls in a React application? What is the SAPUI5/OpenUI5 version you are currently using or are you just getting started?
I can run my tests with webpack 3 again and see if I can make some adjustments for compatibility. However, in general, it might not be super easy to integrate UI5 controls in a react application. Do you already have a plan on how you want to do this?
Additionally, to the react code you would have to load the full UI5 core which might be too much, for example, to just use a UI5 button.

- Chris

**Comment by areinmeyer** [comment]
Hi Chris,

We're (SAP Concur 👋 ) prototyping an Analytics project that uses the SAPUI5 (no particular version at the moment) to pull some data from SAP Analytics Cloud.  While we probably don't need the full UI5 code for that, I think a lot of the theming and layout we will need.  

So I'm trying to merge our stack of React/Webpack to display some widgets that would be coming out of SAP Analytics Cloud.  It's not ideal of course, but I'm trying to see how far we can go before we hit blockers and then assess where we are at.

**Comment by cevou** [comment]
You might want to have a look at https://github.com/SAP/ui5-webcomponents. This might be a much better fit to integrate with an existing React codebase.
